INSERT OR IGNORE INTO tags (name, slug, domain, description, is_seed) VALUES
('Caste', 'caste', 'sociology', 'Caste hierarchies, mobility, and conflict.', 1),
('Identity Politics', 'identity-politics', 'sociology', 'Political action based on identity categories.', 1),
('Urbanization', 'urbanization', 'sociology', 'Cities, migration, and urban transformation.', 1),
('Middle Class', 'middle-class', 'sociology', 'Middle class aspirations, anxieties, and power.', 1),
('Social Movements', 'social-movements', 'sociology', 'Collective action and protest politics.', 1),
('Public Institutions', 'public-institutions', 'policy', 'State institutions, legitimacy, and reform.', 1),
('Democracy', 'democracy', 'policy', 'Democratic process, representation, and accountability.', 1),
('Education Policy', 'education-policy', 'policy', 'Schooling, higher education, and policy design.', 1),
('Science Policy', 'science-policy', 'policy', 'Science, technology governance, and regulation.', 1),
('Agrarian Policy', 'agrarian-policy', 'policy', 'Rural economy, farmers, and land policy.', 1),
('Welfare State', 'welfare-state', 'policy', 'Social protection, redistribution, and public goods.', 1),
('Law and Justice', 'law-and-justice', 'policy', 'Legal institutions, rights, and justice.', 1),
('Secularism', 'secularism', 'policy', 'Religion-state relations and pluralism policy.', 1),
('Development', 'development', 'policy', 'Competing models of growth and welfare.', 1),
('Ritual and Symbol', 'ritual-and-symbol', 'anthropology', 'Meaning systems, symbols, and ritual life.', 1),
('Memory', 'memory', 'anthropology', 'Collective memory, forgetting, and historical narration.', 1),
('Everyday Life', 'everyday-life', 'anthropology', 'Ordinary practices and lived experience.', 1),
('Knowledge Systems', 'knowledge-systems', 'anthropology', 'Local, scientific, and indigenous epistemologies.', 1),
('Culture and Modernity', 'culture-and-modernity', 'anthropology', 'Tradition-modernity negotiations.', 1),
('Technology and Society', 'technology-and-society', 'cross_cutting', 'Mutual shaping of society and technology.', 1),
('Ecology', 'ecology', 'cross_cutting', 'Environmental thought, climate, and sustainability.', 1),
('Nationalism', 'nationalism', 'cross_cutting', 'Nation, belonging, and symbolic politics.', 1),
('Pluralism', 'pluralism', 'cross_cutting', 'Coexistence, diversity, and democratic difference.', 1),
('Public Sphere', 'public-sphere', 'cross_cutting', 'Media, discourse, and public reasoning.', 1),
('Ethics', 'ethics', 'cross_cutting', 'Normative frameworks and moral inquiry.', 1);
